server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuyanshen/aispringcloud.git
          search-paths: config
          username: 763010522@qq.com
          password: 225010wu
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
